### ISSUE TITLE
LDAPS Implementation Crashes the server - Need to implement LDAPS again when we can

### ISSUE THREAD

**Issue by Mctalian** [synergistic-silobusters/flintandsteel#173]
Two similar-looking issues that can occur in a variety of combinations (i.e. only issue 1, only issue 2, both issue 1 and 2):

The first issue is ldap related:
```
LDAP connection error: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```
I think I have a fix for it, though I'm not a huge fan of the fix, it might be the only way. Not sure on this yet. I was about to test the fix, but the server crashed at the same time (unrelated to my fix, see next issue).

The other issue actually crashes the server which is not good.
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
 [16:24:24] [nodemon] app crashed - waiting for file changes before starting...
```
I noticed there was an issue logged against node that sounds like what we're dealing with: [nodejs/node#3595](https://github.com/nodejs/node/issues/3595). So I am now reverting back to `0.12.8` node.js until we understand more on this.

It appears to have something to do with idling sockets based on my observations and form what the above nodejs issue talks about.

**Comment by Mctalian** [comment]
Related: https://github.com/nodejs/node/issues/3517

**Comment by YashdalfTheGray** [comment]
Two suggestions, try node 5.x and I'm sure we're using keepalives somewhere with the timed idea update thing that you put in a while ago. Try disabling that and see what happens. I'm not saying that we shouldn't have that feature but I do want to try it.

**Comment by Mctalian** [comment]
Seems to be somehow related to LDAP, at least partially.

Sometimes it crashes the server, sometimes it does not.

I know login stops working after about 15 minutes of the server being up due to an ECONNRESET. I know since I switched to LDAPS, we are using a newer version of ldapjs - this could be the whole cause or just partial. I can try to revert to normal LDAP during Peer programming to see if that fixes this outright. I'll then have to do some digging in ldapjs to see if I can fix that.

**Comment by Mctalian** [comment]
I disabled server-sent events and it still crashed, so I'm fairly certain that is not the cause.

The good news is it might not be related to node.js after all. We shall see, more to come.

**Comment by Mctalian** [comment]
I reverted LDAPS related commits and it appears that the random crashes disappeared. I will try to upgrade node back to 4.2.2 tomorrow and let it run over the weekend. Then I'll rename this issue to more accurately describe the issue.

**Comment by Mctalian** [comment]
I've confirmed that the server stays running for at least 20 minutes on Node v4.2.2 without LDAPS stuff when it used to only stay running for 15minutes. So I think it's confirmed that LDAPS was the issue. I will look into this much later since it's a 3rd party bug.

**Comment by YashdalfTheGray** [comment]
Is the solution to this sitting on a branch somewhere? Do you think we can pull this into master before the MVP? I hesitate to put a milestone on it since we already have LDAP and HTTPS but I was wondering what you were thinking of doing with the code that you had working yesterday?

**Comment by Mctalian** [comment]
Not on a branch yet, can get it in before MVP

**Comment by davethenipper** [comment]
Was this merged in by the main guy yet?

**Comment by Mctalian** [comment]
Yes, I think so. Thank you for the reminder. This will be the next thing I put up for a PR
