### ISSUE TITLE
 As a user I want the ability to report comments or ideas for inappropriateness so that a good environment is maintained

### ISSUE THREAD

**Issue by davethenipper** [synergistic-silobusters/flintandsteel#217]
Acceptance Criteria to come.Acceptance Criteria:
- [ ] Language Filter
- [ ] A way to notify for inappropriateness

**Comment by monotkate** [comment]
Inappropriateness*

**Comment by YashdalfTheGray** [comment]
#234 rolls up under this one. There is no developer value there, ultimately we're all working on making sure people behave.
