### ISSUE TITLE
Complexity Vs Value

### ISSUE THREAD

**Issue by LongArmMcGee** [synergistic-silobusters/flintandsteel#227]
Acceptance Criteria:
~~- [ ] Value Rating~~
~~- [ ] Value Editable by separate Users~~
~~- [ ] Average Value displayed when logged out~~
~~- [ ] Value Input required on idea creation~~
- [x] Complexity Rating
- [x] Complexity Editable by separate Users
- [x] Average Complexity displayed when logged out

~~- [ ] Complexity Input required on idea creation~~

Braun had a good idea for a feature.

As a user, I want to be able to score an ideas complexity/value.

**Comment by Mctalian** [comment]
Oh yeah! That reminds me about what I wrote down! We can bring up a pop up
for when you like an idea that has you input the estimated value vs
complexity, so liking actually does something AND we use the value vs
complexity values (possibly weighted a bit by number of likes as well) to
fill out our top ideas list, instead of just raw likes.

Just an idea but I think it'll fit in pretty seamlessly.

**Comment by LongArmMcGee** [comment]
I see your inspiration for this, but I think assigning complexity/value to
an idea is an abstract and difficult value to nail down. So, when a user is
thinking, "Herp derp I like this idea!"
*Click Like*
"Oh god I have to think about this nebulous idea of complexity/value? Ugh
IDK I JUST LIKE THE IDEA"

So, the user goes from a very simple action, to a much more difficult
determination of complexity/value and has to suddenly input a lot of mental
energy when it wasn't expected.... to counter my own point, we could simply
add a 'Do this later' button.

**Comment by monotkate** [comment]
To that point I have a feeling that some people would panic and just not like it because they don't want to figure out complexity 🙁

**Comment by YashdalfTheGray** [comment]
I agree with Matt and Miranda here, liking is something very simple and it doesn't have to have a purpose. It's just to say, I read this thing, I like what it's saying and that's what I want to express. So I don't think that we should add another dialog to the like button. 

I think we should run some "magic" algorithm that would take the number of likes, backs, comments, updates and the number of people on the team, plus the last time the idea was updated to come up with a score. We already have all of this data, I think we can write some heuristics to predict how "talked about" an idea is without asking the user for more data.

**Comment by Mctalian** [comment]
Your proposed algorithm has no value or complexity and going forward I
think that will be most important. I'd almost rather JUST use value and
complexity to increase the value of our "score" while keeping the
complexity of calculating the "score" low.

The liking thing was just a thought. Not married to it. Perhaps likes will
be somewhat important as we add search capabilities like sorting. People
can sort by likes, etc. But that's for another time.

**Comment by YashdalfTheGray** [comment]
True but I think we can predict at least the value of the idea, or at least what the userbase thinks is valuable to invest time in, that's pretty easy to predict. We could add some metrics on the website and be able to have something like the "controversial" category on Reddit. 

We could also look at the text going in the comments and watch for some words (server side) and update the complexity score. t think there are enough interactions with an idea that we have, I think we're going to be busying up the idea if we add something else. Plus I think we have a good set of interactions anyway. 

Not trying to start an argument, just my current thoughts, I'm not married to any of them totally.

**Comment by monotkate** [comment]
Could we add a value/complexity function outside of likes? Like a rating? Value: ?/5 starts Complexity: ?/5 stars. Keep it simple but disconnected from likes. This could help with the idea of an algorithm as well. Display it somewhere on the ideas page potentially.

**Comment by monotkate** [comment]
Or maybe it's part of backing an idea? Because at that point you're committing to it. We can also have the idea user add what they think it is (and ultimately sort by it potentially) and then have backers adjust that. I like keeping the complexity of value and complexity low though, while increasing the value to us. 😜

**Comment by Mctalian** [comment]
It should just be it's own thing in my opinion.

**Comment by LongArmMcGee** [comment]
I should have added some context. This comp/val chart is something that came up during the kimbro meeting this past friday. We would use it to directly influence people managers (probably director level?) to pick which ideas they want to dedicate resources to during the 'Innovation Planning' phase of their SAFe PI sprint. So, we don't want to infer this data, we want careful consideration and discussion going into these metrics.

**Comment by monotkate** [comment]
closed in PR#331
