### ISSUE TITLE
As a developer I want to be able to manage my website so that I can maintain events and interactions

### ISSUE THREAD

**Issue by davethenipper** [synergistic-silobusters/flintandsteel#232]
Acceptance Criteria:
- [ ] To Come

Notes:
Administrator accounts? Separate application? Doing it in code is out, tedious + lots of room for error.
Requirements that need changed:
Events
Remove other interactions
Update FAQ

Cons for administrator:
Need lots of checks for admin profile, bogs us down for flint and steel.  
Decision: Make a separate app. Start this in Phase 2.

**Comment by YashdalfTheGray** [comment]
This should be marked as an epic and handled somewhere else. Once we create the new admin app, we'll use the issues over there to track work there.
