### ISSUE TITLE
As a user, I want to have my data secured against unauthorized modification so that my authored data can be protected. 

### ISSUE THREAD

**Issue by davethenipper** [synergistic-silobusters/flintandsteel#256]
This story is to make our rest API more secure. Yash, are you able to fill this in?

Edit by Yash: I'm jacking this comment so that I can add a checklist. 

- [x] Generate a uuid on the server for each user
- [x] Store the uuid into the user object in mongo
- [x] Pass uuid from the client for anything uses the `POST`, `PATCH` and `DELETE` HTTP verbs
- [x] Keep all the `GET` endpoints unprotected to be able to read data
- [x] Unprotect the `POST /users/login` endpoint
- [ ] Protect the `GET /users/:id` endpoint. No one should be able to pull user data without authentication (This may be tricky and might require user-agent access tokens instead so this might only send required information with no access token).
- [ ] Front End changes

**Comment by YashdalfTheGray** [comment]
Yep, I can do it.

**Comment by YashdalfTheGray** [comment]
Done.
