### ISSUE TITLE
As an Innovator, I want my ideas to be backed up, So that they are not lost due to unforeseen circumstances

### ISSUE THREAD

**Issue by davethenipper** [synergistic-silobusters/flintandsteel#259]
Acceptance Criteria:
- [ ] Our Database is backed up
- [ ] Our Database Backup is secure

**Comment by YashdalfTheGray** [comment]
How about 
"As an Innovator,
I want my ideas to be backed up,
So that they are not lost due to unforeseen circumstances. "
We have to try and find why the user thinks something is valuable to them instead of why we think it is valuable to the user.

**Comment by YashdalfTheGray** [comment]
By the way, the card title credit goes to Kyle.
