### ISSUE TITLE
As a user, I want to be able to format the text description of my idea.

### ISSUE THREAD

**Issue by LongArmMcGee** [synergistic-silobusters/flintandsteel#264]
When describing my idea it is often necessary to format some text to better convey information. Typical formatting includes line returns to create rudimentary lists.

**Comment by LongArmMcGee** [comment]
We have also discussed implementing markdown scripting which would solve this in a much more comprehensive manner.

**Comment by Mctalian** [comment]
A stop gap solution would be to `split` the description on `\n` and do an `ng-repeat` with `<p>` for each element in the resulting array of descriptions. The newlines exist in everyone's current descriptions, but the nature of HTML ignores it.

Another option is to try `ng-bind-html` to see if it properly formats newlines. If not we could replace `\n` with `<br/>` and it should work.

These are quick fixes while we look into/implement markdown.
