### ISSUE TITLE
Innovate Logo

### ISSUE THREAD

**Issue by alanlgirard** [synergistic-silobusters/flintandsteel#279]
I got bored and decided to play around with a possible logo.  Comment away on if any strike your fancy or maybe one can be tweaked.  Open to all suggestions.

![ra-innovate-logo](https://cloud.githubusercontent.com/assets/4032278/12738626/5ee013ae-c930-11e5-86e7-f8600067944a.gif)

**Comment by monotkate** [comment]
My favorites are 1 and 5, but I'm a fan!

**Comment by Mctalian** [comment]
Wow these look great! I'll give my choices in a moment

**Comment by Mctalian** [comment]
Alright, 4 is my least favorite.

Then 2.

Then 3.

Then 7.

Then 5.

Then 6.

Then 1. I like 1 a lot.

**Comment by YashdalfTheGray** [comment]
I like 1 and I also like 4.

**Comment by LongArmMcGee** [comment]
Fantastic work, Alan! We should let you be bored more often.

I would like to see 1 with a more spaced out font for the word 'innovate' like 6. I think that would be a winner!

Unnecessary ranking:
I'm not a fan of 7 and 3 is a worse vesion
5 is a worse version of 1
 6 > 2 
I'm meh about 4

So I've learned that I like symmetry.

**Comment by Mctalian** [comment]
I'd be interested to see @LongArmMcGee's suggestion about a modified 1. I don't think I'll like it, but maybe I'm incorrectly visualizing.

**Comment by alanlgirard** [comment]
I will whip up that variation tonight.  If Rockwell didn't block RDP sessions outside the network then I would make it now. #INeedToPurchaseAPersonalLaptop

**Comment by davethenipper** [comment]
I like anything that has the lightbulb as the 'O'.

**Comment by davethenipper** [comment]
I also like 3 & 7

**Comment by alanlgirard** [comment]
@bcbrennecke what do you think about the logos?

**Comment by bcbrennecke** [comment]
1 is by far my favorite, then 5, then 4.  These are so awesome!

**Comment by alanlgirard** [comment]
Quick modification.  Everyone comment away @monotkate @Mctalian @YashdalfTheGray @LongArmMcGee @bcbrennecke @davethenipper 

![image](https://cloud.githubusercontent.com/assets/4032278/12769694/db60f5bc-c9e7-11e5-98e7-2bd7c1355022.png)

**Comment by LongArmMcGee** [comment]
I looove these. I think 6 and the new 3 are the best. Chelsey likes 6 as
well.

Quick modification. Everyone comment away @monotkate
<https://github.com/monotkate> @Mctalian <https://github.com/Mctalian>
@YashdalfTheGray <https://github.com/YashdalfTheGray> @LongArmMcGee
<https://github.com/LongArmMcGee> @bcbrennecke
<https://github.com/bcbrennecke> @davethenipper
<https://github.com/davethenipper>

[image: image]
<https://cloud.githubusercontent.com/assets/4032278/12769694/db60f5bc-c9e7-11e5-98e7-2bd7c1355022.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/synergistic-silobusters/flintandsteel/issues/279#issuecomment-178930871>
.

**Comment by alanlgirard** [comment]
Just as a heads up the latest image is just 1 from the original with the expanded text on both black and white for comparison aka 1=3 and 2=4

**Comment by bcbrennecke** [comment]
I'm a huge fan of 1 and 3.  We should have the option of each, and they look awesome

**Comment by Mctalian** [comment]
The black background isn't another option for me it's an alternative to the
logo we choose as in we use both.

I like the top pair. But an anonymous third party said they didn't read
innovate due to the light bulb. Mostly the globe though. Perhaps drop the
globe?

**Comment by alanlgirard** [comment]
The basic of basic but it does get the point across

![image](https://cloud.githubusercontent.com/assets/4032278/12770149/09a174de-c9ec-11e5-983d-991dd1217c7a.png)

**Comment by bcbrennecke** [comment]
Maybe lightbulb with no globe?  The lightbulb is a good signature

**Comment by YashdalfTheGray** [comment]
I like the white background ones so I'm for the 3 and 4. I'm also really digging the clean look of the white background innovate icon without the globe bulb.

**Comment by alanlgirard** [comment]
Globe removed @bcbrennecke 

![image](https://cloud.githubusercontent.com/assets/4032278/12770322/7789ea48-c9ed-11e5-9a6b-c87f278cc8c7.png)

**Comment by YashdalfTheGray** [comment]
White background again. Also, can we have one with a transparent background? Maybe just the bulb as the icon image for the top right left of the website? Although that seems like a UX anti pattern at this point.

**Comment by LongArmMcGee** [comment]
That looks a lot cleaner and might help make the 'o' easier to read.

**Comment by alanlgirard** [comment]
The logo has a transparent background. Just showing the possible contrasting backgrounds that it could have for other media such as the tvs etc

**Comment by YashdalfTheGray** [comment]
Ah nice!

**Comment by monotkate** [comment]
I'm a huge fan of the black but see it as not integrating well into what we have.  Personally like it better with the globe and don't see the legibility issue, but it's cleaner without.  Might space RA a little bit back from the bulb though.  I don't love how close it is.  Love the spaced out Innovate

**Comment by alanlgirard** [comment]
Everything is done in illustrator so its all vector graphics that can be scaled to any size without pixelation as an FYI also

**Comment by YashdalfTheGray** [comment]
Ooh, very nice, Illustrator is awesome!

**Comment by bcbrennecke** [comment]
I think they're both great.  I don't see white/black as an alternative.  They're the same logo on a different background, we can use both!

**Comment by Mctalian** [comment]
Agreed, they aren't meant to be contrasting options, it's just if we ever
have marketing material that needs a black background we have that option.
Correct @alanlgirard?

Anyway I like the most recent version. It has my vote.

**Comment by alanlgirard** [comment]
The logo has a transparent background. It can be placed on any background color you desire! Aka don't worry about the background color!

**Comment by YashdalfTheGray** [comment]
Seconding the most recent version.

**Comment by Mctalian** [comment]
When are these making an appearance? It'd be awesome if we could get this on the next push to prod (which honestly needs to happen before Thursday because I'll be out of town).

**Comment by alanlgirard** [comment]
I can throw up a quick PR later today/tonight to get the logo swapped out

**Comment by bcbrennecke** [comment]
Woo! I'm excited for the new logo
