### ISSUE TITLE
Logging User Statistics

### ISSUE THREAD

**Issue by alanlgirard** [synergistic-silobusters/flintandsteel#283]
Implement user statistics logging especially for e-week

Possible Logging
- First time logged in
- Number of visits
- Number of interactions (idea creation, edit, backs, comments, etc)

**Comment by davethenipper** [comment]
MKE just suggested a way to track everyone who submits an idea during E-Week/ideation events, and then followup with an email reminder to participate in the challenge.

**Comment by Mctalian** [comment]
Hmm... not a whole lot of time to get that in.

We can just query the database manually and send out a generic email. We
don't need to write any code for that.

**Comment by alanlgirard** [comment]
@Mctalian We might want to look into storing the users location that is in LDAP just so we have that to query on also for the time being.

**Comment by davethenipper** [comment]
Yeah, writing no code sounds good to me.  Keeping it manual for something
that we will theoretically be doing once.

**Comment by davethenipper** [comment]
Is Google Analytics enough to close this?

**Comment by Mctalian** [comment]
Should be if we make one minor change. Just need to track user-ids which I
read up on and know how to do.

**Comment by Mctalian** [comment]
And we also need to add something for interaction tracking which I also
read up on and think I know how to do.

So some additions needed but Google Analytics should cover all our needs.
