### ISSUE TITLE
As a subject matter expert, I would like to subscribe to certain tags, so that I can be notified of brand new ideas related to my expertise.

### ISSUE THREAD

**Issue by Mctalian** [synergistic-silobusters/flintandsteel#292]
This is a feature request from a user, here is their example:

> Could users subscribe receive emails when certain tags are used. For example, if someone tags #Jenkins, that is an idea I would like to see right away.

**Comment by monotkate** [comment]
I like this :+1: 

Of course we need to add notifications in general.  Step 1.

**Comment by Mctalian** [comment]
Yeah my response to their request was that we'll have notifications in some
capacity, details may vary. Didn't want to make promises we couldn't keep,
but I do like this idea and can see us going through with this.

Once we begin planning phase 2, we'll prioritize work.
