### ISSUE TITLE
More jank on the front page of the app

### ISSUE THREAD

**Issue by YashdalfTheGray** [synergistic-silobusters/flintandsteel#296]
<img width="398" alt="screen shot 2016-02-09 at 10 13 42 am" src="https://cloud.githubusercontent.com/assets/3102848/12920262/e9518654-cf15-11e5-8cdf-4dd9df94e3dc.png">

Steps to reproduce
* go to the front psge

**Note**: This is *specifically* not MVP.

**Comment by Mctalian** [comment]
That's the only way the add ideas md-button would stay when scrolling the
sidenav. If you can get that working in a different way, then that's all
you. This was intentional, perhaps due to angular material bugs, but it's
definitely not incidental "jank."

**Comment by YashdalfTheGray** [comment]
Ooh okay. That's fine and after a refresh, it does go away. So I think it's only on the first load of the page. Alright, simple enough. I'm closing this.

**Comment by Mctalian** [comment]
Something to keep in mind, though. I'm sure there are better ways to do it
now.
