### ISSUE TITLE
Upgrade to Node 4.3.0 or 5.6.0 due to Security Vulnerabilities

### ISSUE THREAD

**Issue by Mctalian** [synergistic-silobusters/flintandsteel#303]
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/

I'll do this ASAP on production. But I think we need to update our README and stuff like that to make sure it's calling out the correct version.

**Comment by YashdalfTheGray** [comment]
On it.

**Comment by YashdalfTheGray** [comment]
Done, commits ce82f393cc555730217ac6a53fe05f7bc414335e, 9b097dc9e7d9a2da08e268db62221dc228391038 and 4d952701ae02c760410f8cec544eaa1e3321d479. Check them out and see if I missed anything.
