### ISSUE TITLE
Mock for Proposed Home Page Redesign

### ISSUE THREAD

**Issue by Mctalian** [synergistic-silobusters/flintandsteel#304]
I've discussed this with @bcbrennecke, @YashdalfTheGray, and showed a quick picture to @davethenipper 

Here's some pics. We'll be discussing this Wednesday at the stand-up. Goal of that stand-up is to "Green Light" this so we can get moving on it.

#### Home, Logged Out
![mock_home_loggedout](https://cloud.githubusercontent.com/assets/5081281/13067503/a376846c-d43e-11e5-8701-4f10118b4af2.PNG)

#### Home, Footer (Remains the same at the moment)
![mock_home_footer](https://cloud.githubusercontent.com/assets/5081281/13067498/9add4ebc-d43e-11e5-87ad-5a0b6b6673b0.PNG)

#### Home Logged In
![mock_home_loggedin](https://cloud.githubusercontent.com/assets/5081281/13067494/8f367c6e-d43e-11e5-9577-e7438747b47b.PNG)

Since the sidenav is disappearing, some other pages will look different as well:

#### Create
![mock_create](https://cloud.githubusercontent.com/assets/5081281/13067508/ba272e8c-d43e-11e5-8fee-f28cb9a054d0.PNG)

#### Browse
![mock_browse](https://cloud.githubusercontent.com/assets/5081281/13067510/bfcb21b8-d43e-11e5-8023-9c70378dabe1.PNG)

#### Learn
![mock_learn](https://cloud.githubusercontent.com/assets/5081281/13067512/c6b51902-d43e-11e5-8956-0263ed5a0443.PNG)

#### Idea
![mock_idea](https://cloud.githubusercontent.com/assets/5081281/13067514/cc282366-d43e-11e5-943a-4fda2f97e534.PNG)

I will say, for being a mock, this is pretty much functional... (albeit a bit messy) so theoretically, if we want this to be good to go for E-Week... I'd just have to clean some stuff up (like a test or two I broke by yanking some wires). This currently lives on my `front-page-redesign` branch.

So anyway, Thoughts?

Tagging other devs I hadn't tagged:
@alanlgirard @monotkate

**Comment by monotkate** [comment]
Wait, so no more word cloud?  @alanlgirard  and I had discussed redesigning color wise too.  We were playing around with some of the coloring and it could make a HUGE difference to make our site look modern instead of......grey.  

My input is that I like the concept for the first page, but it looks really..... old/dull from a UX standpoint.  If we're going to redesign, we need to do more to make it look modern.  

Also, I know it's a mock, but really not a fan of the layout for the cards.  Why is there so much empty space and the identicon is so big?

**Comment by bcbrennecke** [comment]
Can we add images into this redesign?  We can give the user a choice of 30 stock images to choose from, not let them upload their own.
This could really upgrade the look of our homepage.  We could turn trending ideas into something more  like the top of kickstarter.com.
We also can get rid of the browse page, no reason to keep it with this.
Huge fan.

**Comment by Mctalian** [comment]
@monotkate, No more word cloud. The only focus of our site at the moment, and very likely the primary focus going forward, is "ideas". So while the word cloud was a cool new thing, it didn't really highlight anything about what the site was.

I'm fine with a recoloring.

I fear "UX" is becoming a very overloaded term within our group. This is the concern I had in the meeting yesterday. UX is a broad topic and I don't think any of us are near a level of understanding needed. It's much more than just following a spec, it's about user-centered design, design thinking, usability tests, user interviews, etc. Very little of which we've actually done.

The cards are using some of the new features of `md-card` in v1.0.5 of angular-material. It's very much "stock" and can be adjusted, but the biggest thing missing, as @bcbrennecke mentioned, is images:

https://www.kickstarter.com/ scroll down to "what's popular"
https://www.indiegogo.com/#/picks_for_you in the "top picks for you section"
https://www.rockethub.com/ "featured projects" (don't hover over a card there, I think it's awful)
https://fundrazr.com/ in "trending"
http://www.ulule.com/ scroll down a bit.
https://material.angularjs.org/latest/demo/card down in the "card action buttons" section, the bottom-right-most example.

So yes, it's a mock. I didn't look into how to make it fancy, but there is an obvious pattern that ALL successful crowdsource sites are using and I think it's silly not to replicate a working pattern.

This mock is more centered around layout/flow than anything. It follows a lot of the patterns for material sites that use cards, and also the single FAB (floating action button) in the bottom right corner is a commonly-used pattern for "Creating a new something" in many Google apps on your phone.

**Comment by monotkate** [comment]
I agree.  I guess in terms of UX I was just referring to appearance.  I think one of the things our site is lacking right now is personality.  It's got some cool functionality but it looks anemic.  I wasn't trying to overload UX, so I'll replace it with front-end :smile: 

So the Ulule cards look way better even if you get rid of the pictures on them.  The way they're arranged just make more sense.  I agree with the changeover on the front page, I'm absolutely a fan, but I think we have to be careful about how to plan it.  I feel like that's a sit down redesign discussion, not a week before quick change, but I could be wrong.

On the card front, the author doesn't come before the title on any of them, and if we keep the author name that small, the identicon size needs to match.  I would probably leave it at:

Idea Title
Idea Author
Likes/Backs/Team

It keeps it simple to start without overcomplicating things.  We can add the descriptions in later, but imo it just clutters it right now.  

You know, we could add a default stock image if we wanted to right now.  Like an eweek image for eweek events, etc?  It would look like it's repeating but it would have images?

I feel like I'm being nitpicky.  I'm sorry if I sound nitpicky. :(

**Comment by Mctalian** [comment]
Yeah, I woke up this morning and reconsidered the redesign by next week
thing. Sleepy thoughts convinced me it was ready but this morning I
remembered some short cuts I took.

As far as layout on an actual card, I'm open. But I think the sidenav
should go away in favor of a list on the home screen like this has. Can
look different.

I also think we should have the create button in the lower right.

I think those two are the core changes I'm proposing. Anything else is open
for discussion. Even better if we can break it down into tasks/user stories
somehow so we can all contribute and get it done faster. I think this
should be high priority phase 2, but we'll discuss that later.

Feel free to take what I've got and alter the cards for an improvement on
the mock, I agree they could look a little better, just try to keep those 2
core things the same. Unless we disagree on those then we need more
discussion.

**Comment by monotkate** [comment]
I'm a fan of the sidenav going away.  

What's the reasoning behind the create button in the lower right?  I don't necessarily disagree or agree, I'm just curious.  I feel like lower right is harder to notice then toolbar?

**Comment by Mctalian** [comment]
Check out the material design spec. It's a pretty common practice I think:

[Example](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsVlhxNGJCNTEzNFU/components-buttons-fab-behavior_04_xhdpi_009.webm) (and a bunch of other examples, [Material Deign Spec: FABs](https://www.google.com/design/spec/components/buttons-floating-action-button.html#) )
[Google Inbox](https://inbox.google.com/) (this one even has fancy stuff when you hover over it)
[JetRadar](http://m.jetradar.com/) (albeit, there's is HUGE and I don't like that)

There are probably others, but this is all I could find quickly right now.

**Comment by monotkate** [comment]
I'm ok with that :+1:

**Comment by monotkate** [comment]
Shit, I was going to pull this down and mess with it, but it's not a PR

**Comment by Mctalian** [comment]
Here you go! [`front-page-redesign`](https://github.com/Mctalian/flintandsteel/tree/front-page-redesign)

Just pull that down to your own fork and you're good to go

**Comment by alanlgirard** [comment]
This is a good start but I would suggest that we have a meeting to discuss the layout and flow of the website so we don't have to do redesign after redesign which would be bad especially that we are "live" now with more and more people visiting the site.

**Comment by monotkate** [comment]
Agreed.  I'm messing with it a bit to see what I can come up with for flow, but I definitely think we should have a sitdown to discuss.  Maybe next Friday after Engineer's Week?  We can have a recap on how it went from a dev side of things + redesign moving forwards.

**Comment by Mctalian** [comment]
We will have a discussion.

**Comment by Mctalian** [comment]
After the Fan4, I think we have a direction and this is no longer needed. I am going to close this. Someone can reopen if needed for some reason.
