### ISSUE TITLE
Multiple likes causes top ideas to exceed container

### ISSUE THREAD

**Issue by alanlgirard** [synergistic-silobusters/flintandsteel#315]
![image](https://cloud.githubusercontent.com/assets/4032278/13253974/0a0dcb26-da0d-11e5-90b6-c983b4e2d69d.png)

**Comment by monotkate** [comment]
I just noticed this too.  If we ever get to three digits it will likely get worse :(

**Comment by alanlgirard** [comment]
Closed with PR #322
