### ISSUE TITLE
Clicking out of the "New Back" window causes it to close

### ISSUE THREAD

**Issue by Mctalian** [synergistic-silobusters/flintandsteel#318]
Causes lost data

**Comment by YashdalfTheGray** [comment]
This works as intended. We can pass a config option to `$mdDialog` to restrict the user to use either the close button or the submit button. But you should be able to close out of any dialog by clicking out of it and the material design specs support that.

**Comment by Mctalian** [comment]
I'm saying add the config option. We have a submit button and an "X" in the corner. I think it's ok to disable click-off closure for a dialog with a 500 character input field.

**Comment by monotkate** [comment]
this is a pretty simple change.  I do see the issue and tend to agree at this point.

**Comment by monotkate** [comment]
closed with PR#331
