### ISSUE TITLE
The favicon has a white background, should be transparent

### ISSUE THREAD

**Issue by YashdalfTheGray** [synergistic-silobusters/flintandsteel#319]
<img width="150" alt="screen shot 2016-02-23 at 1 22 10 pm" src="https://cloud.githubusercontent.com/assets/3102848/13261971/918cfa86-da30-11e5-9d42-b465694e32ea.png">

The inside of the bulb can be white but the rest should be transparent. I'm sure this is a very quick fix.

**Comment by alanlgirard** [comment]
I thought that was transparent when I created that :frowning: I can easily fix that

**Comment by alanlgirard** [comment]
Closes with PR #322
