### ISSUE TITLE
Menu button to bring up side nav isn't available when logged in (Toolbar not responsive)

### ISSUE THREAD

**Issue by LongArmMcGee** [synergistic-silobusters/flintandsteel#320]
![image](https://cloud.githubusercontent.com/assets/5709471/13264406/0d32f98c-da3c-11e5-80f3-3ecc3f9a3f32.png)

I'm surprised no one has noticed this. Is there already an issue for it? I didn't see one.

**Comment by Mctalian** [comment]
This is a condensed window correct?

We are aware that the toolbar is not mobile friendly and I do not believe it was created as an issue. We'll use this as the issue we track against.

**Comment by monotkate** [comment]
Is this still an issue since we're nixing the side nav?  Can we close this then @YashdalfTheGray

**Comment by davethenipper** [comment]
Correct, no issue once Alan's responsive toolbar is delivered.

**Comment by davethenipper** [comment]
Responsive toolbar delivered.

No issue anymore
